### ISSUE TITLE
What am I missing? No scores, tags, or any indication it exists outside of settings. Windows 10

### ISSUE THREAD

**Issue by scrambled2** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#3]
I've installed it correctly and triple checked the tools directory. It's all there.
The options in settings show up as well. 
I've installed the File Handling for png files and I've also tried to write out jpg files. 

No score shows up, when the check the png chunk data there is nothing there. Do I have to do something to activate it?

Nothing weird shows up in the command line. 

Attaching images so you can see what I see. I greatly appreciate the help. 

![image](https://user-images.githubusercontent.com/82735473/198250213-726b1bff-c9b2-4138-af7b-2a78ffb18864.png)

![image](https://user-images.githubusercontent.com/82735473/198250442-24700e16-2b5f-4787-a85e-7cca9e0aaef9.png)

![image](https://user-images.githubusercontent.com/82735473/198251160-6586731d-a73b-4604-bd4d-276ee4c80c41.png)

I'm using the 1.5 model with vae. Everything else works fine, and as expected.

**Comment by blackneoo** [comment]
i am facing the same situation as @scrambled2

**Comment by Cubittus** [comment]
See https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3723
The callback that sets the score before saving is not being called.

**Comment by blackneoo** [comment]
@Cubittus i tried the modification locally, but still the same no tags, exif or png chunks

**Comment by Cubittus** [comment]
The score is definitely being written to the png info chunk - I can see it when I drop an image onto the PNG Info tab.
Unfortunately it doesn't seem to show up anywhere else (txt2img, image browser etc).
I'm not sure what the 'tagging' mechanism is supposed to involve - it looks like it sets some sort of windows file properties, but I don't see it appear anywhere in windows explorer.

**Comment by blackneoo** [comment]
@Cubittus Actually you are right, just checked in png info and seems that images after applying the fix do indeed have the info, but strangely as you said information is not loaded in the image browser or on generation from txt2image 🤔 
tagging is definitely not working for me, regardless of jpg or png

**Comment by blackneoo** [comment]
@tsngo why not add it to generation parameters in this section "Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2285121062, Size: 512x512, Model: model" , if someone is using the extension, then they want to see score information for guidance all across (generation, image browser and as file info)
regarding the tags they are not working at all for me, i checked the files and they don't have any tag information in details, properties or when i group

**Comment by blackneoo** [comment]
Actually that fixed it, now tagging works 👍

**Comment by tsngo** [comment]
I pushed a change that should address the category issue. As for the score in generation params I'll have to take a look and see if it's going break anything.

**Comment by StableInquest** [comment]
unfortunately I'm still seeing `Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory` with the latest pull. M1 MacOS.

**Comment by StableInquest** [comment]
still testing on M1, macos. I do not see any new EXIF data on outputted images. Start up simply shows the following messages, settings are toggled to be on, but for the Windows tag setting:

```
Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
Aesthetic Image Scorer: Forcing prediction model to run on CPU
```

**Comment by tusharbhutt** [comment]
> still testing on M1, macos. I do not see any new EXIF data on outputted images. Start up simply shows the following messages, settings are toggled to be on, but for the Windows tag setting:
> 
> ```
> Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
```
I get this error on Windows 10 too

**Comment by tsngo** [comment]
There's a bug currently preventing png info and exif saving. See readme

**Comment by StableInquest** [comment]
Anything I can do to help test a fix on M1 Mac?
